### ISSUE TITLE
Devices with no Status Property show Unknown but have valid attributes

### ISSUE THREAD

**Issue by MechEng70** [shbatm/hacs-isy994#34] opened 2020-03-17 19:51 UTC
The motion sensors are reporting, however the temp, humdity and lux are not.  They are on the _118 items. 

![ISY view](https://user-images.githubusercontent.com/11697710/76895825-f7f4af80-684d-11ea-9b7c-fbb140ac8078.png)

![HomeAssistant](https://user-images.githubusercontent.com/11697710/76895847-0347db00-684e-11ea-9f00-2b1aeb66d237.png)

**Comment by shbatm** [comment] 2020-03-18 12:09
When you say not reporting what do you mean?

1. There is only one device created (as screenshot shows above)? This is by design, the multiple entities would be nested together as one "device". They should show up if you click on it.
2. There are no entities being created at all for the sub-devices (they aren't listed in the entity register).
3. The entities are there, but the values aren't updating?

**Comment by MechEng70** [comment] 2020-03-18 14:15
Interesting.  I did get the following when clicking on it.
![Screen Shot 2020-03-18 at 7 12 56 AM](https://user-images.githubusercontent.com/11697710/76969721-00012d80-68e8-11ea-9c33-c142ce1cb577.png)

How does one access the temperature, humidity and lux of these types of devices?  The plan is to automate with the device.

**Comment by shbatm** [comment] 2020-03-21 10:07
For now you should use a Template Sensor to break-out the individual values.

I think this came up before, I'll have to go back and dig for the comment on the forums, but the issue is that the ISY does not report a core Status (`ST`) value for that device, which is what HA uses for the main state.

If you get a chance, please post the Node XML (`/rest/nodes/this_addr`) here. I'll see if I can add a workaround since this has come up multiple times.

**Comment by MechEng70** [comment] 2020-03-21 19:49
I found this multi-row card that works.

![Screen Shot 2020-03-21 at 12 46 23 PM](https://user-images.githubusercontent.com/11697710/77235332-04407b80-6b72-11ea-8689-01baf4edd413.png)
[ZW031_118.txt](https://github.com/shbatm/hacs-isy994/files/4363932/ZW031_118.txt)
[ZW031_1.txt](https://github.com/shbatm/hacs-isy994/files/4363933/ZW031_1.txt)

**Comment by shbatm** [comment] 2020-05-03 04:32
Closing this since you've got a work around and this is a bigger issue with the ISY not presenting a Status property for all devices.

**Comment by shbatm** [comment] 2020-05-08 09:41
Thinking more about this, we need a workaround for devices that don't report an `ST` property. Most NodeServers behave this way which, if the ISY development continues the same path, be becoming more and more prevalent.

**Closed** 2020-09-13 01:13 UTC
